# Cloudflare Workers Configuration for EchoDiary
name = "echodiary"
main = "app/main.py"
compatibility_date = "2024-10-23"

# Python Workers support
[build]
command = "pip install -r requirements.txt"

[build.upload]
format = "service-worker"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "echodiary_db"
database_id = "your-database-id"  # Get from: wrangler d1 create echodiary_db

# KV for Redis-like storage (alternative to Upstash)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"  # Get from: wrangler kv:namespace create "SESSIONS"

# Environment variables (secrets set separately)
[vars]
APP_NAME = "EchoDiary"
APP_VERSION = "1.0.0"
DEBUG = "False"
SESSION_TTL_SECONDS = "7200"
CONTEXT_TURNS_LIMIT = "3"
MOOD_NEGATIVE_THRESHOLD = "3.0"
CHECKIN_DELAY_HOURS = "24"

# Cron triggers for check-ins
[triggers]
crons = ["*/15 * * * *"]  # Every 15 minutes

# Durable Objects for real-time sessions (optional)
# [[durable_objects.bindings]]
# name = "CALL_SESSIONS"
# class_name = "CallSession"

# Routes
[routes]
pattern = "echodiary.workers.dev"
custom_domain = true

# Limits
[limits]
cpu_ms = 30000  # 30 seconds max CPU time

# Static assets (HTML templates)
[site]
bucket = "./static"

# Assets for templates
[[assets]]
binding = "ASSETS"

